
title: Ken Kong's Blog
email: kongly677@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a slow walker, but I never walk backwards.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://linyukong677.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: linyukong677
github_username: linyukong677
avatar: /avatar.jpg
cover_image: /bg.jpg
permalink: pretty

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/