# Setup
title: Linyu Kong's Blog
description: Research is something that everyone can do, and everyone ought to do. It is simply collecting information and thinking systematically about it.
url: https://linyukong677.github.io
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

social:
  name: linyukong677
  links:
    - https://github.com/linyukong677

author:
  name: Lin Yu Kong
  url: https://github.com/linyukong677/
  email: kongly677@gmail.com
